const dynamic = "force-dynamic"
import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { SessionContextProvider } from "./contexts/Session.context";
import { getServerAuthSession } from "@/server/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Lyra Technologies",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} antialiased overflow-y-scroll no-scrollbar`}>
        <SessionContextProvider session={session}>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </SessionContextProvider>
      </body>
    </html>
  );
}
